version: '3.8'
services:
  db-postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: motorwind
      POSTGRES_USER: motorwind_dev
      POSTGRES_PASSWORD: motorwind_dev_password
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
  db-postgres-test:
    image: postgres:14
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: motorwind_test
      POSTGRES_USER: motorwind_dev
      POSTGRES_PASSWORD: motorwind_dev_password
