spring:
  config:
    import: optional:file:.env[.properties]

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}